name: App Builder

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            exe: ModpackInstaller.Desktop.exe
          - os: ubuntu-latest
            rid: linux-x64
            exe: ModpackInstaller.Desktop
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    env:
      Project_Path: ModpackInstaller.Desktop/ModpackInstaller.Desktop.csproj
      App_Id: ModpackInstaller

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish app
        run: |
          dotnet publish ${{ env.Project_Path }} \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -o ./publish

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Pack and Upload directly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          
          # 1. Descarcă release-ul anterior (pentru a genera Delta Updates)
          # Dacă e prima versiune, vpk va ignora automat lipsa release-urilor vechi
          vpk download github \
            --repoUrl "https://github.com/${{ github.repository }}" \
            --token "$GITHUB_TOKEN" \
            --outputDir ./releases || echo "Nu s-au găsit release-uri anterioare, se creează release-ul inițial."

          # 2. Impachetare (acum că are acces la versiunile vechi, va genera și patch-uri)
          vpk pack -u ${{ env.App_Id }} \
                   -v "$VERSION" \
                   -p ./publish \
                   -e ${{ matrix.exe }} \
                   --outputDir ./releases

      - name: Rename Output if linux
        if: runner.os == 'Linux'
        run: |
          cp -r ./releases ./Releases

      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |         
          vpk upload github \
            --repoUrl "https://github.com/${{ github.repository }}" \
            --publish \
            --releaseName "Release $VERSION" \
            --tag "$GITHUB_REF_NAME" \
            --token "$GITHUB_TOKEN" \
            --merge
