name: App Builder Win

on:
  push:
    branches: [main, workflows]
  pull_request:
    branches: [main, workflows]

jobs:
  build:
    runs-on: windows-latest

    env:
      GitToken: ${{ secrets.TOKEN }}
      Project_Path: ModpackInstaller.Desktop/ModpackInstaller.Desktop.csproj
      Wix_Project_Path: MSIPackage/MSIPackage.wixproj
      Wix_Output: MSIPackage/bin/Release/en-US/MSIPackage.msi
      Wix_RenameTo: ModpackInstaller.Desktop_Installer.msi
      Wix_Rename: MSIPackage/bin/Release/en-US/ModpackInstaller.Desktop_Installer.msi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Add WiX 3.14 to PATH
        shell: pwsh
        run: |
          $w = 'C:\Program Files (x86)\WiX Toolset v3.14\bin'
          if (Test-Path $w) { $env:PATH += ";$w" }
          else { Write-Error "WiX not found at $w"; exit 1 }

      - name: Restore .NET project
        run: dotnet restore

      - name: Publish application
        shell: pwsh
        run: dotnet publish ${{ env.Project_Path }} `
          -c Release  `
          -r win-x64  `
          /p:AppGitToken=${{ env.GitToken }}

      - name: Get Project Version
        id: get_version
        shell: pwsh
        run: |
          [xml]$proj = Get-Content ${{ env.Project_Path }}
          $v = $proj.Project.PropertyGroup.Version
          echo "PROJECT_VERSION=$v" >> $env:GITHUB_OUTPUT

      - name: Build MSI
        run: dotnet build ${{ env.Wix_Project_Path }} -c Release -p:DefineConstants="ProductVersion=${{ steps.get_version.outputs.PROJECT_VERSION }}"

      - name: Rename MSI file
        shell: pwsh
        run: Rename-Item -Path ${{ env.Wix_Output }} -NewName ${{ env.Wix_RenameTo }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.PROJECT_VERSION }}
          name: Release v${{ steps.get_version.outputs.PROJECT_VERSION }}
          draft: false
          prerelease:
            ${{ contains(steps.get_version.outputs.PROJECT_VERSION, '-beta') ||
            contains(steps.get_version.outputs.PROJECT_VERSION, '-alpha') ||
            contains(steps.get_version.outputs.PROJECT_VERSION, '-rc') }}
          files: ${{ env.Wix_Rename }}
          body: |
            Download the latest verision of the app by installing the macOs version or the win 64 version.
