name: App Builder (Velopack)

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            rid: win-x64
            exe: ModpackInstaller.Desktop.exe
            channel: ""
      
          - os: ubuntu-latest
            rid: linux-x64
            exe: ModpackInstaller.Desktop
            channel: "linux"
    
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash

    env:
      Project_Path: ModpackInstaller.Desktop/ModpackInstaller.Desktop.csproj
      App_Id: ModpackInstaller

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: Publish app
        run: |
          dotnet publish ${{ env.Project_Path }} \
            -c Release \
            -r ${{ matrix.rid }} \
            --self-contained true \
            -o ./publish

      - name: Install Velopack
        run: dotnet tool install -g vpk

      - name: Pack and Upload directly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          CHANNEL_ARG=""
          
          if [ -n "${{ matrix.channel }}" ]; then
            CHANNEL_ARG="--channel ${{ matrix.channel }}"
          fi
          
          vpk download github \
            $CHANNEL_ARG \
            --repoUrl "https://github.com/${{ github.repository }}" \
            --token "$GITHUB_TOKEN" \
            --outputDir ./releases || true
          
          vpk pack \
            $CHANNEL_ARG \
            -u ${{ env.App_Id }} \
            -v "$VERSION" \
            -p ./publish \
            -e ${{ matrix.exe }} \
            --outputDir ./releases

          echo "--- Structura folderului releases ---"
          ls -R ./releases
          echo "-------------------------------------"
  
          echo "--- Structura folderului releases ---"
          ls -R ./
          echo "-------------------------------------"
        
          vpk upload github \
            $CHANNEL_ARG \
            --repoUrl "https://github.com/${{ github.repository }}" \
            --publish \
            --releaseName "Release $VERSION" \
            --tag "$GITHUB_REF_NAME" \
            --token "$GITHUB_TOKEN" \
            --merge
