name: .NET Core Desktop Release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    env:
      Solution_Name: minecraft-installer.sln
      Project_Path: MyCSharpApp/MyCSharpApp.csproj
      Executable_Name: MyCSharpApp.exe
      Wix_Source_Files: MSI_Builder/Product.wxs
      Wix_Output_Dir: MSI_Builder/bin/Release
      Architecture: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore ${{ env.Solution_Name }}

      - name: Publish application
        run: |
          dotnet publish ${{ env.Project_Path }} `
            -c Release `
            -r win-x64 `
            --self-contained false `
            -p:PublishSingleFile=false `
            -p:TrimMode=link `
            -o Release

      - name: Build MSI with WiX Toolset
        uses: utilitywarehouse/ghaction-wix@v1
        with:
          name: ${{ env.Executable_Name }}
          sourceFiles: ${{ env.Wix_Source_Files }}
          outputDir: ${{ env.Wix_Output_Dir }}
          architecture: ${{ env.Architecture }}

      - name: Get Project Version
        id: project_version
        shell: pwsh
        run: |
          $content = Get-Content -Path "${{ env.Project_Path }}" -Raw
          if ($content -match '<Version>(.*?)</Version>') {
            echo "PROJECT_VERSION=$($Matches[1])" >> $env:GITHUB_OUTPUT
          } else {
            Write-Error "Could not find <Version> tag in $env:Project_Path"
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.project_version.outputs.PROJECT_VERSION }}
          name: Release v${{ steps.project_version.outputs.PROJECT_VERSION }}
          draft: false
          prerelease: ${{ contains(steps.project_version.outputs.PROJECT_VERSION, '-beta') || contains(steps.project_version.outputs.PROJECT_VERSION, '-alpha') || contains(steps.project_version.outputs.PROJECT_VERSION, '-rc') }}
          files: |
            ${{ env.Wix_Output_Dir }}/${{ env.Executable_Name }}.msi
          body: |
            Download the latest **${{ env.Executable_Name }}** and the MSI installer.
