name: .NET Core Desktop Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    env:
      # Paths relative to repo root
      Project_Path: MyCSharpApp/MyCSharpApp.csproj
      Wix_Project_Path: MSI_Builder/MSI_Builder.wixproj
      Wix_Output: MSI_Builder/bin/Release/net8.0-windows/MSI_Builder.msi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Add WiX 3.14 to PATH
        shell: pwsh
        run: |
          $w = 'C:\Program Files (x86)\WiX Toolset v3.14\bin'
          if (Test-Path $w) { $env:PATH += ";$w" }
          else { Write-Error "WiX not found at $w"; exit 1 }

      - name: Restore .NET project
        run: dotnet restore ${{ env.Project_Path }}

      - name: Publish application
        run: dotnet publish ${{ env.Project_Path }} -c Release -r win-x64 --self-contained false -p:PublishSingleFile=false -p:TrimMode=link -p:OutputType=WinExe -o Release

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build MSI via MSBuild
        shell: pwsh
        run: msbuild ${{ env.Wix_Project_Path }} /p:Configuration=Release

      - name: Get Project Version
        id: get_version
        shell: pwsh
        run: |
          [xml]$proj = Get-Content ${{ env.Project_Path }}
          $v = $proj.Project.PropertyGroup.Version
          echo "PROJECT_VERSION=$v" >> $env:GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.PROJECT_VERSION }}
          name: Release v${{ steps.get_version.outputs.PROJECT_VERSION }}
          draft: false
          prerelease: ${{ contains(steps.get_version.outputs.PROJECT_VERSION, '-beta') ||
                         contains(steps.get_version.outputs.PROJECT_VERSION, '-alpha') ||
                         contains(steps.get_version.outputs.PROJECT_VERSION, '-rc') }}
          files: ${{ env.Wix_Output }}
          body: |
            Download the latest **MyCSharpApp.exe** and the MSI installer.
